default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default

stagang:
  <<: *default

production:
  <<: *default
